### PR TITLE
Mongo 3 support

### PR DESCRIPTION
**Pull request by StephenBlackWasAlreadyTaken**
UNTESTED - Dear god someone please test it.

Also I know you usually put things in dev, feel free to move it if needed, I compiled these mongo drivers myself and they DONT support async on mongo3, I assume you dont use async?

### CODE REVIEW

**Comment by StephenBlackWasAlreadyTaken** [comment]
ugh, why are all those commits here, I swear I based off of master and not dev...

**Comment by StephenBlackWasAlreadyTaken** [comment]
@jasoncalabrese if you get a chance

**Comment by jasoncalabrese** [comment]
Yeah, looks like this has lots of stuff from dev, don't think the dev branch will ever get released

**Comment by jasoncalabrese** [comment]
Going to try it using gradle: https://github.com/nightscout/android-uploader/commit/6173b576eebd82f9be0f3fd97015523835e6bbb7

**Comment by StephenBlackWasAlreadyTaken** [comment]
hrm, did they update theirs so it would work with android? Because I had to cram this stuff in and compile it myself

**Comment by jasoncalabrese** [comment]
oh, didn't know that was a custom hacked jar

**Comment by jasoncalabrese** [comment]
In that case we should try dropping your jars in the `hotfix/mongo3` branch, all the tests pass with mongo3 just didn't work at runtime

**Pull request closed without merging**
